const express = require("express");
const router = express.Router();
const db = require("../db/database");
const { verifyToken } = require("../middleware/authMiddleware");

// This endpoint receives token generated by frontend, 
// verifies it, and creates/updates the user in SQLite
router.post("/login", verifyToken, (req, res) => {
  const { uid, email, name, picture } = req.user; // from firebase token
  const userName = req.body.name || name || "";
  
  db.get(`SELECT * FROM users WHERE id = ?`, [uid], (err, row) => {
    if (err) return res.status(500).json({ error: err.message });
    
    if (row) {
      // User exists
      res.json({ message: "Login successful", user: row });
    } else {
      // Create user
      db.run(
        `INSERT INTO users (id, email, name) VALUES (?, ?, ?)`,
        [uid, email, userName],
        function (err) {
          if (err) return res.status(500).json({ error: err.message });
          res.json({
            message: "User created",
            user: { id: uid, email, name: userName }
          });
        }
      );
    }
  });
});

module.exports = router;
